### ISSUE TITLE
Translate view gets into a state where approving translations is broken

### ISSUE THREAD

**Issue by bugzilla-to-github** [mozilla/pontoon#2297] opened 2021-05-28 22:16 UTC
*This issue was created automatically by a [script](https://github.com/mathjazz/bugzilla2github/).*
## [Bug 1713435](https://bugzilla.mozilla.org/show_bug.cgi?id=1713435)
Bug Reporter: @flodolo

Take a translation with multiple pending suggestions, e.g. [this one](https://mozilla-pontoon-staging.herokuapp.com/it/thunderbird/mail/messenger/aboutRights.ftl/?string=211191)

1) When opening the editor, the last suggestion `Test 2` is in the input field.
2)  Now click on the 2nd suggestion, `Test`, then try to approve `Test 2` by clicking directly the green checkmark. You'll get a warning (unsaved changes), click the X to ignore it.
3) Now try to approve the 1st suggestion (`Test 2`). Nothing happens, no errors. You can still approve the 2nd one directly though.

**Comment by mathjazz** [comment] 2021-11-10 21:50
Phew, any chance you could try to provide STR again? Seems like those translations are one.

**Comment by mathjazz** [comment] 2021-12-10 20:21
Piotr also reported he's having trouble approving a string:
https://pontoon.mozilla.org/pl/thunderbird/mail/messenger/accountManager.ftl/?string=233937

This could be related to #2251.

**Comment by eemeli** [comment] 2022-07-31 16:23
@flodolo Is this still reproducible? If I follow the steps you detail above, Pontoon appears to be have just as it should.

**Comment by flodolo** [comment] 2022-07-31 16:29
No, seems to be working correctly now.Message ID:
***@***.***>

>

**Comment by eemeli** [comment] 2022-07-31 21:32
Great! Then I'm going to close this as presumably fixed by some of the refactoring I've done.

**Closed by eemeli** 2022-07-31 21:32 UTC
Labels: P1, bug, checks, FTL
