### ISSUE TITLE
Translation page loads then unloads. "Uncaught (in promise) Error: Unsupported message pattern length 2" in console

### ISSUE THREAD

**Issue by chutten** [mozilla/pontoon#2966] opened 2023-09-21 15:49 UTC
When loading something like https://pontoon.mozilla.org/en-CA/all-projects/all-resources/?status=missing&string=285408 the page loads and then "unloads" (goes to a flat blank bgcolour). I checked the devtools console and saw a couple mentions of

```console
Uncaught (in promise) Error: Unsupported message pattern length 2
    patternAsString https://pontoon.mozilla.org/static/js/translate.min.01da09f5963d.js:33
    genPatterns https://pontoon.mozilla.org/static/js/translate.min.01da09f5963d.js:33
    editMessageEntry https://pontoon.mozilla.org/static/js/translate.min.01da09f5963d.js:33
    EditorProvider https://pontoon.mozilla.org/static/js/translate.min.01da09f5963d.js:33
```

Not sure what's going on.

**Comment by mathjazz** [comment] 2023-09-21 16:17
Thanks for the report!

We actually fixed the issue yesterday (#2964), but it hasn't been pushed to production yet. Thanks for the reminder! The link should now work.

Resolving as dupe of #2954.

**Closed by mathjazz** 2023-09-21 16:17 UTC
