### ISSUE TITLE
Two strings on Pontoon cannot be approved successfully

### ISSUE THREAD

**Issue by Olvcpr423** [mozilla/pontoon#2949] opened 2023-09-02 09:04 UTC
### The problem:
There are two strings that cannot be approved successfully:
1. 278410 (AMO project)
2. 263159 (SUMO project)

### The behavior:
- **1st string**: Though you can approve a translation, the translation you approved will automatically turn "rejected" several days later, and the status of the string turns "Unreviewed".
- **2nd string**: Though you can approve a translation, the status of the string will automatically turn "Unreviewed" several days later. However, unlike the 1st string, the translation you approved before won't turn "rejected". ([screenshot](https://drive.google.com/file/d/1mZJNT6WVodjY-8EeyczNG5WvrVykkm01/view))

### Affected languages:
As far as I know, this problem occurs in all languages that words don't have a plural form, including Chinese Simplified ([1st](https://pontoon.mozilla.org/zh-CN/all-projects/all-resources/?string=278410) & [2nd](https://pontoon.mozilla.org/zh-CN/all-projects/all-resources/?string=263159) string), Chinese Traditional ([1st](https://pontoon.mozilla.org/zh-TW/all-projects/all-resources/?string=278410) & [2nd](https://pontoon.mozilla.org/zh-TW/all-projects/all-resources/?string=263159) string) and Vietnamese ([1st](https://pontoon.mozilla.org/vi/all-projects/all-resources/?string=278410) & [2nd](https://pontoon.mozilla.org/vi/all-projects/all-resources/?string=263159) string) (Japanese and Korean haven't translated these strings yet).

**Comment by mathjazz** [comment] 2023-09-22 18:49
It turns out this is actually a duplicate of #2744.

**Closed by mathjazz** 2023-09-22 18:49 UTC
Labels: P2, bug
