### ISSUE TITLE
FTL: Issues when copying from LOCALES tab

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2569] opened 2022-07-08 13:50 UTC
1) Clicking on a translation in the LOCALES tab copies the string with the ID
2) Copying a complex string (with attributes) will copy the entire string (full FTL syntax, including the ID) in the attribute currently selected (e.g. try with [this one](https://pontoon.mozilla.org/fr/firefox/browser/browser/aboutPrivateBrowsing.ftl/?string=197034))

**Comment by flodolo** [comment] 2022-07-08 13:51
Note that 1 is already causing errors ([example](https://pontoon.mozilla.org/dsb/firefox/browser/browser/browser.ftl/?search=private-browsing-shortcut-text&string=246215)).

**Comment by mathjazz** [comment] 2022-07-08 13:55
Duplicate of #2567.

**Closed by mathjazz** 2022-07-08 13:55 UTC
