### ISSUE TITLE
Can't approve one specific pretranslation for Italian

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2872] opened 2023-06-05 15:39 UTC
I think something went wrong while I was approving a group of translations, and now:
* The header shows 0 strings missing for Thunderbird.
* [This link](https://pontoon.mozilla.org/it/thunderbird/all-resources/?status=pretranslated&string=280892) shows 1 pretranslated strings waiting for review.

When I try to approve it, the UI becomes empty (gray background) with the tiny green line on top, and the log has a not very nice error

```
 Jun 05 15:36:51 mozilla-pontoon app/web.1 Internal Server Error: /translations/approve/
Jun 05 15:36:51 mozilla-pontoon app/web.1     return self.cursor.execute(sql, params)
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/database_psycopg2.py", line 64, in execute
Jun 05 15:36:51 mozilla-pontoon app/web.1     return super(CursorWrapper, self).execute(sql, parameters, *args,
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/database_dbapi2.py", line 38, in execute
Jun 05 15:36:51 mozilla-pontoon app/web.1     return self.__wrapped__.execute(sql, parameters,
Jun 05 15:36:51 mozilla-pontoon app/web.1 DETAIL:  Failing row contains (230743, 0, 44, -1, 111, 6955, 9610277, 43, 0, 0).
Jun 05 15:36:51 mozilla-pontoon app/web.1 The above exception was the direct cause of the following exception:
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
Jun 05 15:36:51 mozilla-pontoon app/web.1     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/framework_django.py", line 563, in wrapper
Jun 05 15:36:51 mozilla-pontoon app/web.1     return wrapped(*args, **kwargs)
Jun 05 15:36:51 mozilla-pontoon app/web.1     return f(request, *args, **kwargs)
Jun 05 15:36:51 mozilla-pontoon app/web.1     return view_func(request, *args, **kwargs)
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/contextlib.py", line 79, in inner
Jun 05 15:36:51 mozilla-pontoon app/web.1     return func(*args, **kwds)
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/pontoon/base/models.py", line 3589, in approve
Jun 05 15:36:51 mozilla-pontoon app/web.1     self.save()
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/pontoon/base/models.py", line 3956, in adjust_all_stats
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/pontoon/base/models.py", line 580, in adjust_stats
Jun 05 15:36:51 mozilla-pontoon app/web.1     self.save(
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/base.py", line 739, in save
Jun 05 15:36:51 mozilla-pontoon app/web.1     self.save_base(using=using, force_insert=force_insert,
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/base.py", line 776, in save_base
Jun 05 15:36:51 mozilla-pontoon app/web.1     updated = self._save_table(
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/base.py", line 858, in _save_table
Jun 05 15:36:51 mozilla-pontoon app/web.1     return filtered._update(values) > 0
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/query.py", line 802, in _update
Jun 05 15:36:51 mozilla-pontoon app/web.1     return query.get_compiler(self.db).execute_sql(CURSOR)
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
Jun 05 15:36:51 mozilla-pontoon app/web.1     cursor = super().execute_sql(result_type)
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
Jun 05 15:36:51 mozilla-pontoon app/web.1     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
Jun 05 15:36:51 mozilla-pontoon app/web.1     return executor(sql, params, many, context)
Jun 05 15:36:51 mozilla-pontoon app/web.1     raise dj_exc_value.with_traceback(traceback) from exc_value
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
Jun 05 15:36:51 mozilla-pontoon app/web.1   File "/app/.heroku/python/lib/python3.9/site-packages/newrelic/hooks/database_dbapi2.py", line 38, in execute
Jun 05 15:36:51 mozilla-pontoon app/web.1     return self.__wrapped__.execute(sql, parameters,
Jun 05 15:36:51 mozilla-pontoon app/web.1 DETAIL:  Failing row contains (230743, 0, 44, -1, 111, 6955, 9610277, 43, 0, 0).
```

**Comment by mathjazz** [comment] 2023-06-05 15:54
Seems like a dupe of #2263. I tried to approve the string again and it worked.

**Closed by mathjazz** 2023-06-05 15:54 UTC
