### ISSUE TITLE
Do not detect selectors on numbers without any CLDR categories as plurals

### ISSUE THREAD

**Issue by eemeli** [mozilla/pontoon#2805] opened 2023-03-20 10:42 UTC
As discussed in https://github.com/mozilla/pontoon/pull/2802#discussion_r1141760251, this change ought to be applied to both the front-end and the back-end.

**Comment by mathjazz** [comment] 2024-12-14 13:54
Dupe of #2178.

**Closed by mathjazz** 2024-12-14 13:54 UTC
Labels: javascript, P3, enhancement
