### ISSUE TITLE
[feature request] Mark notifications as read manually only

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/pontoon#2506] opened 2022-05-03 15:30 UTC
As Pontoon user I would like to keep my notifications as unread until later. As a localizer unread notification may work as a backlog of new strings to work on, as a translator/manager the notification may contain information about what I need to review.

The current behaviour of Pontoon UI now is, that notification get marked as read the very moment I click the bell icon to see them. I would like to be able:
- disable to automatic marking of all notifications as read and mark them as unread manually
- as a bonus mark the notifications as unread one by one, not always all of them

This is of course open to discussion, because I understand this opens a way for people keeping so many unread notifications, that the never actually read any, or notice there are some fresh ones.

**Comment by flodolo** [comment] 2022-05-03 15:32
Potentially a dupe of #2108?

**Comment by mathjazz** [comment] 2022-05-03 23:21
@MikkCZ Please re-open if you don't see this as a dupe.

**Closed by mathjazz** 2022-05-03 23:21 UTC

**Comment by MikkCZ** [comment] 2022-05-04 06:14
Yes, it is, and both opened by me. Sorry for that. :D
