### ISSUE TITLE
File renames in git repos are not well handled

### ISSUE THREAD

**Issue by eemeli** [mozilla/pontoon#3406] opened 2024-10-10 12:48 UTC
`pontoon.sync.repositories.git.changed_files()` doesn’t deal well with renames, as `git diff --name-status` will print an R for those, and we’re only handling `A`, `D` and `M` lines. If that happens, the resource doesn’t get included in Pontoon.

This came up for me while testing the sync refactor locally with `mozilla-vpn-client`, but only because I’m running my local tests updating projects from a late-June snapshot to now. In prod, the file addition (`en/addons/message_update_v2.24/strings.xliff`) and removal (`en/addons/message_update_v2.23/strings.xliff`) that overall read as a rename landed in separate PRs (mozilla-l10n/mozilla-vpn-client-l10n#462 and mozilla-l10n/mozilla-vpn-client-l10n#463) with 18 minutes in between, which was probably enough time for a sync run.

We should probably check that Pontoon’s list of resources matches what's in each repo. Renamed files will get included if they change after a rename, but as the files with the old name are removed from disk, we won't notice any later changes with them, and they'll stick around.

**Comment by flodolo** [comment] 2024-10-10 12:54
I did report this a while ago (#3063).

This has been happening for a while in VPN, because git interprets a removal+new file as a move+change.
https://github.com/mozilla/pontoon/issues/3063#issuecomment-1888962478

**Comment by mathjazz** [comment] 2024-10-10 15:24
Closing as dupe of https://github.com/mozilla/pontoon/issues/2211.

**Closed by mathjazz** 2024-10-10 15:24 UTC
