### ISSUE TITLE
Comments sidebar shouldn't take focus when moving to a new string

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2745] opened 2023-02-02 16:14 UTC
Open the translation UI with multiple strings, then click on the COMMENTS tab (top right corner).

Now translate a string, or simply move down. The focus will move from the text edit area to input the translation to the input field for the string comment.

**Comment by mathjazz** [comment] 2023-06-15 10:25
Dupe of #2626.

**Closed as completed by mathjazz** 2023-06-15 10:25 UTC
Labels: P2, bug
