### ISSUE TITLE
"Same translation already exists" when trying to change the access key attribute

### ISSUE THREAD

**Issue by flodolo** [mozilla/pontoon#2973] opened 2023-10-03 17:51 UTC
https://pontoon.mozilla.org/ia/firefox/browser/browser/preferences/preferences.ftl/?search=certs-thirdparty-toggle&string=285757

This string had an empty access key: I put a letter, but couldn't save it. I had to switch to FTL source code to do it.

**Comment by mathjazz** [comment] 2023-10-03 19:30
Hm, I am unable to reproduce this here:
https://mozilla-pontoon-staging.herokuapp.com/sl/firefox/all-resources/?string=282148

To clarify, the original string looked like this:

```fluent
certs-thirdparty-toggle =
    .label = Permitte que { -brand-short-name } fide automaticamente in le certificatos radice de tertie partes que se installa
    .accesskey = { "" }
```

@eemeli In addition to the bug, I believe this is a UX regression? We should show a warning that one of the values is empty when trying to save such message.

**Comment by flodolo** [comment] 2023-10-03 19:42
> To clarify, the original string looked like this:
> 
> ```ftl
> certs-thirdparty-toggle =
>     .label = Permitte que { -brand-short-name } fide automaticamente in le certificatos radice de tertie partes que se installa
>     .accesskey = { "" }
> ```

That's correct. This is the fix landing
https://hg.mozilla.org/l10n-central/ia/rev/6099eefa2bc7432c3e0914f82e3915e5ac7d3fea

Indeed, I can't reproduce on stage with the string you linked to 🤔 

I'm on a different machine, and even trying in prod (approving the old translation, then trying to submit a different translation) works. Not sure if that was a temporary issue on the other machine.

**Comment by flodolo** [comment] 2023-10-04 13:45
Tested again on the same machine and can't reproduce. Either it happens only in very specific cases, or something was temporarily broken (e.g. some cached JS?).

**Comment by eemeli** [comment] 2023-10-06 10:14
I've not been able to reproduce this either. Closing this for now, but happy to reopen if the problem recurs.

> In addition to the bug, I believe this is a UX regression? We should show a warning that one of the values is empty when trying to save such message.

The current practice is to consider any content in a Fluent value or attribute to qualify the whole message as not-empty. The check for this was added in #2675. Previously empty attributes may indeed have resulted in errors, due to stringifying as invalid Fluent. If you think we should change the current behaviour, that should be tracked as a separate bug.

**Closed by eemeli** 2023-10-06 10:14 UTC
Labels: P2, bug

**Comment by flodolo** [comment] 2023-10-06 10:19
> If you think we should change the current behaviour, that should be tracked as a separate bug.

I think we should, as [a few locales](https://test.flod.org/checks/) are starting to commit translations with empty attributes
