### ISSUE TITLE
Issue with string removal for mobile

### ISSUE THREAD

**Issue by Delphine** [mozilla/pontoon#2384] opened 2021-12-08 23:53 UTC
Not sure if this is the place to file, please let me know.

**Summary:**
Removing strings from [values/strings.xml](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/res/values/strings.xml) in the mobile repo does not actually remove them, if locale does not maintain work on Pontoon

**Context:**
@gabrielluong recently removed deprecated strings from [values/strings.xml](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/res/values/strings.xml).
During this work, it was realized that some strings seem to stick around for locales that haven't maintained their work in Pontoon for a while

**Example (from Slack discussion with gl and Sebastian):**
lint-baselint.xml contains a lot of extra translations: https://searchfox.org/mozilla-mobile/source/fenix/app/lint-baseline.xml#979-5190 
What this means is that there is a string in some limited locales, but not in values/strings.xml. 
For example, https://searchfox.org/mozilla-mobile/search?q=inactive_tabs_survey_not_interested_option&path= is only found for AR, BR, and IN
Put another way, the strings are still found in the translations but not in the default locale (values/strings.xml)

If you look at the strings/locales that still contain those strings, they seem to not have been updated in a while (in this case not since those strings were removed and added to the lint baseline file). So the guess is that the string files will only be updated if the project is actively getting edited (on Pontoon). A removal from the base strings.xml will not trigger a roundtrip on its own

**Conclusion/Guess:**
Strings are only removed if the project is actively maintained in Pontoon, after their removal in the mobile repo

**Ask:**
Is there a workaround to avoid this on Pontoon side?
Does it really matter if these strings aren't removed until the next time a locale updates their work on Pontoon? One thing I can think of on l10n side, is that these strings still show up on Pontoon, so people can still update/review them, which is extra work for nothing.
CCing @gabrielluong for more info if needed

**Comment by flodolo** [comment] 2021-12-09 06:16
> Removing strings from [values/strings.xml](https://github.com/mozilla-mobile/fenix/blob/main/app/src/main/res/values/strings.xml) in the mobile repo does not actually remove them, if locale does not maintain work on Pontoon

This is by design in all projects: Pontoon only commits to files when there is another activity, to avoid unnecessary noise in history. IMO, a linter should not report extra strings in localization files.

Those strings are not in the source content, so they won't show up in Pontoon (you can verify it by searching one of the strings, [example](https://pontoon.mozilla.org/ga-IE/firefox-for-android/all-resources/?search=app_name_private_3&string=214629)).

**Comment by eemeli** [comment] 2021-12-09 14:24
> Does it really matter if these strings aren't removed until the next time a locale updates their work on Pontoon?

I don't think it really matters. As Flod mentions, the strings won't show up on Pontoon due to missing from the source, and will get removed once something else happens in the target locale.

**Comment by flodolo** [comment] 2021-12-09 14:42
One more note: performance would become an issue. When I touch all hg repos, sync for Firefox alone can take up to 1h, and that's just reading. In this case, we would be writing to 150 repositories, or do X commits on one monorepo.

If we need to do this every time we add or remove new strings from projects, it would simply break down.

**Comment by Delphine** [comment] 2021-12-09 16:17
That's all great to know! This thread will at least help us not have the same conversation over again in the future, so thanks for both of your input.
CC @gabrielluong and @pocmo: we can close the loop on this.
Closing this issue soon, unless you'd like to add anything

**Comment by flodolo** [comment] 2021-12-09 16:56
Note: there's only potential risk.

Let's say a locale isn't updated in 1 year. A year from now, devs reintroduced a string with the same ID, but different text. I have a feeling Pontoon will still do the right thing (show the new string without translation, because the old one was marked as obsolete in the DB), but it might be worth double checking.

In any case, I think it's an acceptable risk.

**Closed** 2021-12-11 00:07 UTC

**Comment by gabrielluong** [comment] 2021-12-29 00:26
@flodolo I am wondering if this means it is okay to address the linter issue by removing the extra translation that are no longer valid as identified by https://searchfox.org/mozilla-mobile/source/fenix/app/lint-baseline.xml#979-5190 or if we should ignore them completely.

**Comment by flodolo** [comment] 2021-12-29 20:10
You should ignore them, we shouldn't touch localized files.
