### ISSUE TITLE
"Insight" at project level stopped working since March

### ISSUE THREAD

**Issue by peiying2** [mozilla/pontoon#2618] opened 2022-09-06 17:17 UTC
It appears that the Insight tab stops collecting new information since March. This affects all projects except Firefox.

https://mozilla-pontoon-staging.herokuapp.com/zh-TW/firefox-relay-website/insights/

**Comment by mathjazz** [comment] 2022-09-06 17:38
Closing as duplicate of #2540, which fell through the cracks.

**Closed by mathjazz** 2022-09-06 17:38 UTC
